"""Enhanced models

Revision ID: 2e25d6bcb06b
Revises: 6b6db26079b9
Create Date: 2025-04-06 19:45:46.860006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e25d6bcb06b'
down_revision = '6b6db26079b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_logger', schema=None) as batch_op:
        batch_op.alter_column('task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('task_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_task_logger_logged_at'), ['logged_at'], unique=False)
        batch_op.create_foreign_key(None, 'task_manager', ['task_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('task_manager', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_manager_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_manager_status'), ['status'], unique=False)
        batch_op.drop_constraint('task_manager_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_username_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.create_unique_constraint('user_username_key', ['username'])

    with op.batch_alter_table('task_manager', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('task_manager_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_task_manager_status'))
        batch_op.drop_index(batch_op.f('ix_task_manager_created_at'))

    with op.batch_alter_table('task_logger', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_task_logger_logged_at'))
        batch_op.alter_column('task_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('task_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
